import { Box, Text, Divider } from '@chakra-ui/react';
import Link from 'next/link';

export default function InterviewWithVastAbrupt() {
    return (
        <Box textAlign="left" pl="2rem">
            <Text pb={6} pt={20}>
                <b>3:AM Magazine:</b> To begin with a question into a practice of anonymity that seems somewhat out of the ordinary: Most of your contributors go by their given names, and seldom as pseudonyms, while VA’s publishers remain anonymous. Considering that the opposite has traditionally been the case, with the publisher assuming the role of spokesperson for its shadow authors, are there any factors or conditions which make anonymity significant to VA’s publishing practices?
            </Text>
            <Text pb={6} >
                <b>Vast Abrupt:</b> The way VA emerged is one of them. But there is also a practical dimension. Anonymity is one of the elements that vitalized the early internet, and which was lost in the wake of the implementation of increasingly visual interfaces in the early 2000s. If you look at the history of Western philosophy, all of the interesting escape vectors—vectors of contagion and communication—arrive under a critique of the visual, of the equation of knowledge with light, of the user-tool distinction that the distance required to underwrite visual perspective puts into play. The hyper-visualisation of online culture re-instantiates this old covenant between sight, knowledge and identification, and brings with it the misconception that humans are the users and machines are their tools, not to mention a new regime of surveillance and the entire edifice of oppressive online identity politics. VA wants to step outside of this return to ancient power structures and re-engage the potency of the unknown and unknowable. Serving as an anonymous dissemination node for feverish self-assembly, mordant infection, and enthusiastic madness is its way of upholding a certain form of resistance to the perversity of the Facebook megalopolis. We never ask our writers to identify themselves, and rarely know their ‘real’ names unless they themselves choose to add them to the texts. And even among those who use their names, there is a tendency to write as if one is only a carrier for other, more abyssal incursions.
            </Text>
            <Text pb={6}>
                <b>3:AM:</b> Is there a singular ideological set, then, that VA and its contributors have in common? Or do the principles enumerated here preclude that?
            </Text>
            <Text pb={6}>
                <b>VA:</b> Fragmentation and dissolution seem to be the emergent points on which the texts of VA ironically converge. There is no ideology, but perhaps a processual methodology of experimentation can be said to unify the project. VA knows nothing, so why should it pretend to enunciate a path for others to follow? In terms of the presence of mythical thinking in the works, the modality of unbelief could also be said to haunt the site. An idea or an aesthetic will concretize itself if it is taken up by enough nodes in a system, in just the same way that it will dissolve or degrade into unreality when the opposite occurs. If anything, all of these commonalities—fragmentation, experimentation and unbelief—are anti-ideological. The only agreement is the persistence of unresolvable disagreements. 
            </Text>
            <Text pb={6}>
                <b>3:AM:</b> VA has received as much negative criticism as praise, seemingly for its scholarly approach to parody and pessimism, though perhaps “serving as an anonymous dissemination node” and allowing itself to become an unknown/unknowing carrier for all sorts of obscure, weird, and deranged agendas might actually have something to do with it. Bruce Sterling has <Link href="https://www.wired.com/beyond-the-beyond/2018/01/arch-stanislaw-lem-like-parodies-going/" target="_blank">stated</Link> that VA reads “like outsider art…” and also went on to say “I kind of like them…but I don’t know how, or to whom, I would ever recommend them.” What are VA’s thoughts on criticisms such as these?
            </Text>
            <Text pb={6}>
                <b>VA:</b> The level of consternation legible in the various reviews and responses scattered around the internet is quite astonishing. Those who hate it don’t really seem to be able to articulate why (“they’re high”, “why would I want to read something that destroys my faith in thinking itself?”, “[it’s] like a sick joke”, “the description that comes to mind is addled”, “it makes no sense”—all direct quotations), and the same goes for the more positive comments we’ve received, like the one written by Bruce Sterling. The general mood is a sort of confused ambivalence, which is something VA deeply appreciates. Catalysis is good, and ultimately recognisable under the sign of unintelligibility. VA has had no clear idea what it is doing (or what is being done through it) since the ‘beginning’, but this in itself is enough of a positive indication that something interesting is going on.
            </Text>
            <Text pb={6}>
                <b>3:AM:</b> Before we dive deeper in the occultural philosophy of Vast Abrupt, can you tell us about its name and where it was derived from? What is its significance?
            </Text>
            <Text pb={6}>
                <b>VA:</b> ‘Vast abrupt’ is curious for a number of reasons. First of all, it’s a paradox, and its acronym—VA—enciphers this quality with toothy diagrammatic clarity. Paradoxes encode interesting temporal anomalies—circular causation, auto-production, recursion, templexity, anachronic annexation (or ‘plagiarism by anticipation’)—all of these things undermine coherent subjective unity and present the beguiling puzzle that actively attempting to produce a certain effect often leads to its opposite. Fragmentation is key here, and the Latin etymology of ‘abrupt’, deriving from the verb abrumpere denotes a movement of ‘breaking off’ or ‘away’ from something. So there’s a double meaning there that links cybernetic paradox with the breaking up of things, and indicates, between the two, a preference for instability over stability at a systemic level.
            </Text>
            <Text pb={6}>
                Secondly, the ‘vast abrupt’ is probably best known as one of Milton’s infamous substantives or nominalised adjectives (like ‘darkness visible’ and ‘palpable obscure’), which turns up early in his famous epic poem, Paradise Lost, to describe the dimensionless realm between Heaven and Hell presided over by Chaos. There is a tangential connection to the strange cosmogony presented in Paradise Lost that, as readers of Vast Abrupt might know, harbours an occult connection to carbonation, alchemy, the Fall, and ultimately, to the gradual unfurling of terrestrial capitalism—programmed from the future by the black and tartareous flows of Pepsi Capital, puppeting the ill-fated English poet—who died of a peptic ulcer—and transforming him into a seer.
            </Text>
            <Text pb={6}>
                Milton, in light of this revelation, must also be added to that secret list of writers who cannot be said to have written, truly, as themselves. The name inevitably inspired the website’s first submission by the wildly brilliant Thomas Moynihan, and the project was launched with a series interrogating these connections over seven consecutive days—a travesty of the Biblical creation story.
            </Text>
            <Text pb={6}>
                <b>3:AM:</b> There’s a lot to digest here. We must return to the series by Thomas Moynihan, but first, how do these temporal anomalies materialize and what are their implications for truth and myth, which, in light of this, become almost fluid, inseparable? These elements come up often in VA’s texts. For example, you have published an essay by Lyotard, translated for the first time in English, that speaks of the ‘decadence’ of truth, and a serial article entitled, “Synthetic Fabrication” which touches on the generative myth of certain political outcomes. How do all these tie together?
            </Text>
            <Text pb={6}>
                <b>VA:</b> The tableau of the present is the enemy, and it is within the zone of myth where past and future meet and forge a pact against it. More properly, it is through myth that something from the past is called up, something is extracted from the past to make it move in a new way, and it is through this movement that the still-unknown—and unknowable—future is opened.
            </Text>
            <Text pb={6}>
                To give a concrete example, Marx describes how the bourgeois revolutions conducted themselves through the mythic identification with actors from the past: Camille Desmoulins, Danton, Robespierre, St. Just, Napoleon, the heroes of the old French Revolution, performed their historical task in Roman costumes and phrases. And earlier still, he finds it in the activities of Cromwell—an identification with the trials, ordeals, and even language of the Old Testament. In both the English uprisings and in the French Revolution, the same dynamism can be detected. The struggle comes under the sway of myth, constituting a falling-back into the past in a manner that allows one to act, after which the myth itself supposedly falls away and modernity begins to take root.
            </Text>
            <Text pb={6}>
                Milton, in light of this revelation, must also be added to that secret list of writers who cannot be said to have written, truly, as themselves. The name inevitably inspired the website’s first submission by the wildly brilliant Thomas Moynihan, and the project was launched with a series interrogating these connections over seven consecutive days—a travesty of the Biblical creation story.
            </Text>
            <Text pb={6}>
                Marx seems to think that the proletariat revolution will divest itself of the ‘mythic veil’, and that eventually it will execute its historical task without recourse to an identification with something other than itself. Georges Sorel, the great author of Marxist heresies, pushes back on the hard stadialism of the master’s philosophy, and in doing so dissolves the fixity of myth and allows it to diffuse across the historical field. Myth here is the true reality of political activity, and insofar as Marx seeks to purge it from the future through the proletariat’s revolutionary fury, he breathes new life into it by draping the revolution in millenarian cloth. So again, we arrive at a situation in which the neat flight of time’s arrow is undermined by all manner of strange loops and sideways maneuvers that change their character depending on how one is looking at them. Is the temporal pact forged by myth an indicator of time’s linearity—by cracking the present open to the future—or does it suggest the movement of the future back into the present (after all, the resurrection of the past within the present can never perfectly copy the past, and thus is intrinsically new)? Or does the loop back to the past produce, as the diagram of history, a cycle? It is all of these and none of them—the cycle opens history and the opening undermines the cycle, both coming together in the time of the spiral.
            </Text>
            <Text pb={6}>
                <b>3:AM:</b> The seven-part serial by Thomas Moynihan is entitled, <Link href="https://vastabrupt.com/series/cosmic-dyspepsia/" target="_blank">“Cosmic Dyspepsia & Divine Excrement: or, an Essay Unveiling the Teleoplexic Identity of Miltonic Chaos, Capitalist Nigredo and Alchemical Pepsi Cola™”</Link>. As the title suggests, this long essay mashes late capitalist consumer culture with cosmic horror tropes. It’s one of the most brilliant and schizotypal articles your website has to offer. How was this article conceived, and why target Pepsi Cola™?
            </Text>
            <Text pb={6}>
                <b>VA:</b> As with any good contagion or arcana, it only made ‘sense’—if at all—in reverse. Retrospect is our only aperture on these things, inasmuch as we cannot see where they are going yet. Who knows what might yet be extracted from this vein, this ‘chaos rude and indigest’? It was only a few months after the writing of the series had been completed that the famed <Link href="https://www.atlasobscura.com/articles/found-lobster-pepsi-logo-tattoo" target="_blank">‘Pepsi Lobster’</Link> was dredged up from the sea in November 2017 (this episode was retconned to form the series’ prologue—and frame the ensuing content—although it actually happened afterwards). We could only take this as a vindicating sign of success.
            </Text>
            <Text pb={6}>
                Part synchromystical demoniac screed, part stress-test concerning the byzantine potentials of academic ‘writing’, part total and utter nonsense, the serial “Cosmic Dyspepsia” thus emerged from a meditation upon a winding tradition of texts, whose connection to fact-stating realities is self-consciously apocryphal ‘at best’ and strategically deceitful ‘at worst’: a somewhat unseen genre that operates by prodigally playing with its own status as existence’s ‘dubia’. The serial began its life, in now long-lost chat logs, through discussions upon that confounding spuria of PepsiCo lore: the <Link href="https://www.goldennumber.net/wp-content/uploads/pepsi-arnell-021109.pdf" target="_blank">Arnell ‘Breath-Taking’</Link> document. Published in 2008, it is still not known if it was a hoax or not (talk at the time within the advertising community focused on how this camouflaging of intention only intensified its spread).
            </Text>
            <Text pb={6}>
                The document, packaged as part ‘Brand Stratagem’ and part ‘Metaphysic Manifesto’, contains reference to things such as ‘PEPSI GLOBE DYNAMICS’, comparing the design of the Pepsi logo and Earth’s gravitational fields. Whether a leak of marketing hubris or perfectly poised viral injection, the document’s strange contents were instantly reminiscent of the investigations of Earth’s molten core by one Dr. Barker. Barker’s breakthrough was ‘Geotrauma’—the study of how geodynamics are the mnemonic ledger of trans-organic traumata, or, a rheology of mineral anguish, etc.
            </Text>
            <Text pb={6}>
                Another unlikely place to find ‘geotraumatics’ in action, it was noted, was Milton’s <em>Paradise Lost.</em> The blind poet’s curious metaphysics (more heterodox than many Milton scholars might like to admit) sees matter’s default state as undigested chaos: ergo, chaos is internal to material realities rather than oppositional or alien, and God is re-conceived as a constant process of digestion that keeps things in ordained place and function. Milton, for his own part, was preoccupied with digestion—to the point of transposing it geotraumatically within his epic’s cosmogony—because, for him, digestion was itself pure trauma: he had a peptic ulcer, proving eventually fatal. To return to PepsiCola™, it was then discovered that Pepsi was itself originally made and marketed—by Bradham in the 1890s—to cure exactly this ailment. Hence the name, ‘Pepsi’. Pepsi promotes eupepsia, as opposed to dyspepsia, because it palliates peptic ulceration. The author then asked, what would a splicing of Arnell’s document and <em>Paradise Lost.</em> look like? From this initial jump spark, everything pinwheeled and the piece, as we have been told, wrote itself: synchronicities and occultural synapses emerged, reticulated, and reticulated again, to create a sprawling network of links.
            </Text>
            <Text pb={6}>
                So that is the story of the series’ retrospective conception as it was divulged to VA. It formed an (attempted) practice in deceitful world-building, or, heterocosmic manufacture: looking to inspirations from Browne’s Musæum Clausum to Borges’ ‘Tlön, Uqbar, Orbis Tertius’. The idea being to fabricate another shard of ‘reality-apocrypha’. Each of its fragments functioned as a virus: creating fungibility between the substructures of plausibility and implausibility. Such texts utilize the packaging of fact-stating media/genres (academic writing, museum catalogues, ostensive lists, editorial frames) as strategic cover to instead breed counter-factual experimentations.
            </Text>
            <Text pb={6}>
                <b>3:AM:</b> That is perhaps the most deliciously messed up and chaotic birth of a document ever conceived. As it could easily have been an abortion the mere fact that it exists – masterfully weaving in and out of that imperceptible boundary between real and fiction, a new genre that operates “by playing with its own status as existence’s ‘dubia’”, as you aptly put it – is in itself significant. Which brings us to the prefix “trans-”, a modifier that appears quite frequently within these texts. Often, it accompanies some form of metaphysical stance. What’s your stance on “trans-” in terms of threshold crossing, and the embodied practices that go with this?
            </Text>
            <Text pb={6}>
                <b>VA:</b> To take the two parts of your question separately—first, from a metaphysical stance. The Latin trans means to be across, on the far side, beyond (on the Outside), compared to the Latin cis, which means to be on this side—on the Inside. Transness is distinct from cis-ness in the sense that while the latter is already finished and static, the former denotes a perpetual state of transition: it’s dynamic. The prefix doesn’t demand completion in any sense, and is perhaps best defined by a vectorial schema—temporally, as a present wed to a future, and spatio-temporally, as a desire to cross-over to the Outside. For something to be trans, it has to already involve an inherent trauma, an alienation from itself.
            </Text>
            <Text pb={6}>
                Second, transness from an embodied stance can be understood as the diagonal practice of this crossing-over—from the Inside of ordered, metaphysically-complete humanism (cis-ness) towards an open state of becoming. To occupy the prefix ‘trans-’ in our contemporary moment is to be the ultimate hacker—whether that practice is understood to be focused on hacking the socio-linguistic and literary codes that govern representation, or the body itself, right down to the molecular level. It can also be grasped very pragmatically in the sense of escaping or exiting from the division of gender into the masculine and the feminine, the one and the zero (understood as a binary), the subject and the object, etc., and towards an infinite becoming. It is the wielding of identity as a hyperstition (via the mechanism of unbelief), rather than being operated on by identity as a superstition. It could also be understood as a denunciation of the ideological purity of identity politics, both on the ‘reactionary’ and ‘progressive’ sides, and instead, as taking possession of identity (again, both discursive and biological) as something desired rather than something imposed. Transness plugs a desire for exit from the cisnormative phallogocentric logic of gender into the libidinal economy of technocapital. It is a bargain with the pharmaceutico-medical industry (a decidedly restricted but nonetheless productive matrix) to produce a future which never existed (the ‘correct’ bodily development of the trans person). In doing so, the trans-occupant enters a state of becoming, a dissolution where there is no end (transition never truly ends, trans people have to take hormones their entire lives), where one is suspended over an abyss of pure chaos and death, perpetually in communication with danger and vulnerability, and constantly at risk of being subsumed into the repressive/reterritorializing desire of humanism to impose and crystallize identity. Transness is riding the winds of the vast abrupt—locked in an infinite game, played in multiple realities, and never, ever to be concluded.
            </Text>
            <Text pb={6}>
                <b>3:AM:</b> There’s also a strong affinity for gothic aesthetics throughout these articles. Beyond its engagement with occultism, what other purpose does VA’s brand of gothicism serve?
            </Text>
            <Text pb={6}>
                <b>VA:</b> The gothic involves an aesthetic of recursion and intensive detail. A bright darkness, a decadent outsideness. We can see this no matter where we look throughout its history: the explosion of Gothic architecture across medieval Europe as a result of the weakening influence of feudal authority and the new freedoms of capitalism; the fragmenting of the subject that is central to the Gothic novel born out of a burgeoning industrial revolution; the k-goths already looking for the outside of a new online environment. Instead of an aesthetics of repetitive cycles, or the simplification of modernity into clear-cut lines, the Gothic presents a tangled line, a spiral, which closes upon itself without reaching the completion of eschatology.
            </Text>
            <Text pb={6}>
                <b>3:AM:</b> All of the aforementioned articles are available on your website as downloadable PDFs. Are there foreseeable plans to compile these works into a physical release at some point or is the internet your preferred medium?
            </Text>
            <Text pb={6}>
                <b>VA:</b> Yes and yes. Is that a contradiction?
            </Text>
            <Text pb={6}>
                <b>3:AM:</b> It doesn’t have to be. We look forward to seeing these works in physical form. Before we end this segment, we would like to know how VA goes about selecting its contributors? Are articles commissioned? Or, must one first pledge allegiance to your <Link href="https://vastabrupt.com/series/web-lobster-deathcult-fragments-liturgies/" target="_blank">Lord of Lobsters</Link>?
            </Text>
            <Text pb={6}>
                <b>VA:</b> Infectious ideas find hosts amenable to them. VA doesn’t select its contributions, nor does it commission texts. Connections are made without any of the usual administrative apparatus that accompanies orthodox editorial procedures. The writers insinuate themselves—always from the side, in the shadows, on the edge, the unhinged interzones of the net—that interstitial textual space that Sadie Plant once described as the inheritance of women. Some form of synergetic magic seems to run the show, VA doesn’t really understand how it works. Of course, there are ways to contact VA, as you yourselves have discovered, and VA takes everything that signals to it seriously. There are no allegiances, only leakages, converging flows, synergetic breaks, shed skins, dismembered bodies.
            </Text>
            <Text pb={6}>
                <b>Denihilism OS, prophet of the Web.Lobster [[Death Cult]], has issued the following proclamation:</b> ‘The message of the lobster had already bled into the minds of the technømystics, waiting to be channeled & transcribed, sent directly through fiber optic cable to the digital caves & deserts.’
            </Text>
        </Box>
    )
}